### ISSUE TITLE
 Service ResponseFactoryInterface not found exception

### ISSUE THREAD

**Issue by devarun** [prooph/event-store-http-middleware#9]
While trying to access `event store http api`, it fails with the following error:

`request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "Interop\Http\Factory\ResponseFactoryInterface"." at /var/www/web/vendor/symfony/dependency-injection/Container.php line 274`

In prooph/event-store-http-middleware/src/Container/Action/FetchStreamNamesFactory.php->get (line 25)

```
$actionHandler = new FetchStreamNames($container->get(EventStore::class), $container->get(ResponseFactoryInterface::class));
```

Also https://github.com/http-interop/http-factory it is deprecated now.

**Comment by prolic** [comment]
Wanna submit a PR?
